### ISSUE TITLE
Optimizing two-phase cd

### ISSUE THREAD

**Issue by solidsmokesoftware** [solidsmokesoftware/physicr#1]
Currently single phase collision detection is faster than two phase. Need to figure out what's slowing it down

#Done
Storing Shapes vs Ints in the hashmap? #Doesn't seem to matter
Spatial hash key .to_i is expensive need to remove that in favor of floor division #Done
Try hard coded bucket grabs #Done
Try building array instead of join #Done but still need to optimze

#Unfinished
Try collision callback inside/after get to avoid return 
Try collision space / event system #Need to do this
Try having entities in multiple buckets, one get but higher movement costs #Fairly big change will try this later

**Comment by rebuilding-patrick** [comment]
Nested loop for grabbing multiple buckets

Try hard coded bucket grabs

Try having entities in multiple buckets, one get but higher movement costs

**Comment by rebuilding-patrick** [comment]
Try replacing hash with pair (index, shape)

Try replacing hash with grid (full array)

Brute force -> simple world
Hash -> infintie world
Grid -> fast world

**Comment by rebuilding-patrick** [comment]
Return array

Try array of arrays
Try building array instead of join
Try collision callback inside/after get to avoid return
Try collision space / event system
